version: "3.9"
services:
  app:
    build: app
    links:
        - db
    ports:
      - "50000:5000"
  db:
    image: mysql:8.0.21
    ports:
        - "30000:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: warehouse
    volumes:
        - "./db:/docker-entrypoint-initdb.d"